name: Build Ultimate64Viewer

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # This allows manual triggering

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    
    - name: Build Ultimate64Viewer
      run: |
        cd xcode
        xcodebuild -scheme Ultimate64Viewer \
                   -configuration Release \
                   -derivedDataPath build \
                   -archivePath Ultimate64Viewer.xcarchive \
                   archive
        
        xcodebuild -exportArchive \
                   -archivePath Ultimate64Viewer.xcarchive \
                   -exportPath ./export \
                   -exportOptionsPlist ExportOptions.plist
    
    - name: Create DMG
      run: |
        cd xcode
        # Create a temporary directory for DMG contents
        mkdir dmg-contents
        cp -R export/Ultimate64Viewer.app dmg-contents/
        
        # Create Applications symlink for easy installation
        ln -s /Applications dmg-contents/Applications
        
        # Create the DMG
        hdiutil create -volname "Ultimate64Viewer" \
                       -srcfolder dmg-contents \
                       -ov -format UDZO \
                       Ultimate64Viewer.dmg
    
    - name: Upload DMG as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Ultimate64Viewer-DMG
        path: xcode/Ultimate64Viewer.dmg
    
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: xcode/Ultimate64Viewer.dmg
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
